### ISSUE TITLE
모니터링 시스템 구축하기 - 1

### ISSUE THREAD

**Issue by Bue-von-hon** [f-lab-edu/MSG-lab#23]
어플리케이션 모니터링 시스템 구축의 첫번째 스텝입니다.
여기서는 스프링 액추에이터를 통해 모니터링 데이터를 제공하고, 프로메테우스에서 이를 가져가는 동작을 구현합니다.

`/actuator/prometheus` 이런식으로 endpoint를 제공합니다.

application.yml 파일에 아래와 같은 정보를 입력한다면, 알맞은 endpoint를 노출할 수 있습니다.
```yml
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, etc...
```

prometheus는 docker를 이용하여 구동합니다.(spring-app은 당연히 우리가 만든 MSG-lab...)
`docker-compose up`을 이용하여 구동시킬 수 있게 구현합니다.
구동시키는데 필요한 명령어가 많으니 Dockerfile을 활용합니다.
이대 prometheus의 타겟 설정으로 도커밖의 localhos를 설정해야합니다.

아래와 같이 타겟을 잡아주면, localhost 타겟 설정이 가능합니다.(host.docker.internal 일종의 키워드입니다.)
```yml
scrape_configs:
  - job_name: 'spring--app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
```
