### ISSUE TITLE
[중요] 스프링 프로필 적용이 안되는 버그

### ISSUE THREAD

**Issue by Bue-von-hon** [f-lab-edu/MSG-lab#67]
현재 아래와 같이 멀티 프로필이 설정되어 있습니다.
하지만 `java -jar -Dspring.profiles.active=dev ...` 이렇게 액티브 프로필을 지정해도 해당 설정이 활성화되지 않는 문제가 있습니다.
활성화를 위헤 불필요한 `profiles.group`을 지우고, 불필요한 `""`(콤마)도 지우면 좋겠습니다.
아래와 같이 변경해주세요.

as-is
```yml
#default
spring:
  profiles:
    group:
      "develop": "dev"
# 각종 기본 설정

---

# dev
spring:
  config:
    activate:
      on-profile: "dev"
# 각종 dev 설정
```

to-be
```yml
#default
spring:
# 각종 기본 설정

---

# dev
spring:
  config:
    activate:
      on-profile: dev
# 각종 dev 설정
```
