### ISSUE TITLE
application.yml에 충분한 설명을 포함하기

### ISSUE THREAD

**Issue by Bue-von-hon** [f-lab-edu/MSG-lab#71]
datasource의 driver와 url은 특정한 형식이 있습니다.
아래와 같이 충분히 설명된 예시가 있다면 좋을것 같습니다.
```yml
  datasource:
    driver-class-name: # 데이터베이스 드라이버 설정, MySQL은 com.mysql.cj.jdbc.Driver
    url: {프로토콜}://{주소}:{포트}/{데이터베이스 이름} # 데이터베이스 접속 주소, 주로 프로토콜은 jdbc:mysql 사용
```
