### ISSUE TITLE
worker 모듈의 RabbitMQ 설정을 기본 프로필에서 dev 프로필로 이동하기

### ISSUE THREAD

**Issue by Bue-von-hon** [f-lab-edu/MSG-lab#75]
기본 프로필에서는 공통된 설정이, dev/real 등의 프로필에는 각각의 환경에 따라 변할 수 있는 설정이 들어가야 합니다.

to-be
```yml
# 아래의 설정이 default에서 dev로 이동되어야 합니다.
rabbitmq:
    host: # 호스트 주소
    port: # 호스트 포트번호
    username: # 유저네임
    password: # 유저 패스워드
```
