### ISSUE TITLE
Prometheus 설정을 동적으로 변경하는 기능 추가하기

### ISSUE THREAD

**Issue by Bue-von-hon** [f-lab-edu/MSG-lab#95]
## 배경
현재 아래와 같이 타겟 설정이 고정되어 있습니다.
타겟은 언제나 생성되고, 추가될 수 있음으로 동적으로 이를 변경할 수 있는 기능이 추가되야할 것 같습니다.
e.g. 테라폼을 이용한 IaC 환경에서는 변경이 흔함

```yml
scrape_configs:
  - job_name: 'spring--app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
```

## 구현할 내용
[블로그 글](https://gurumee92.tistory.com/m/243)처럼 동적으로 변경할 수 있게 수정합시다.
